### ISSUE TITLE
Error while registering, ratelimit

### ISSUE THREAD

**Issue by ecskn** [Mid0aria/SPX#1]
![Error while registering, ratelimit](https://user-images.githubusercontent.com/118984630/203818409-f51195fe-9c26-4ac9-8f23-e4b369595aed.gif)

**Comment by Mid0aria** [comment]
use proxy

**Comment by ecskn** [comment]
> use proxy

Still the same

**Comment by ecskn** [comment]
So what now?

**Comment by Mid0aria** [comment]
use hq proxy ?

**Comment by ecskn** [comment]
It takes me a long time to earn followers. Sometimes I'm waiting even 4 or 5 minutes for one single follower. I want to gain a lot of followers without getting any errors just like yours. I don't know how to get rid of this thing. I did a lot of research but couldn't come to a definite conclusion. I haven't come across anyone else dealing with this error like me. The poor quality of my internet may also be causing this problem.
